---
title: Dragonfly Scenery
timezone: UTC
collections:
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page 
url: http://dragonflyscenery.com
description: London-based set-design, prop and art direction studio working alongside the industry's leading photographers, directors and creatives
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
- bower_components
- config.codekit3
- CHANGELOG.md
- LICENSE.md 
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Dragonfly Scenery and Design Ltd
email: info@dragonflyscenery.com
google_site_verification: 0u9XTYzI8wOtLEO26wdbqmiWdUn5s5f0UYUisdLW7BY
analytics: UA-87668728-1
logo: "/assets/img/layout/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: 
  instagram: 
  twitter: 
  vimeo: 
